name: SLURM Queue Workflow
on: 
  push: 
    branches:
      - 'main'
jobs: 
  queue:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -l {0}
    steps: 

     - uses: actions/checkout@v4
     - name: Get a short version of the GIT commit SHA to use in naming files
       id: getshortsha
       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

     - name: Copy files over to the cluster
       uses: garygrossgarten/github-action-scp@v0.6.0 
       with:
          local: ./
          remote: "/users/r/s/${{ secrets.SSH_USERNAME }}/scratch/JOBS/${{ steps.getshortsha.outputs.sha_short }}"
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
     - name: setup python
       uses: actions/setup-python@v2
       with:
        python-version: 3.11 #install the python needed
     - name: Install dependencies
       run: | 
             python -m pip install --upgrade pip
             pip install -r requirements.txt          
    #  - uses: conda-incubator/setup-miniconda@v3
    #    with:
    #         auto-update-conda: true
    #         activate-environment: anaconda-client-env
    #         environment-file: etc/environment.yml
    #         auto-activate-base: false
    #  - run: |
    #        conda info
    #        conda list
     - name: Execute script to queue job in cluster
       uses: appleboy/ssh-action@v0.1.3
       with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: | 
            cd "/users/r/s/${{ secrets.SSH_USERNAME }}/scratch/JOBS/${{ steps.getshortsha.outputs.sha_short }}"
            module load gcc-9.3.0-gcc-7.3.0-fjzqkyt
            python3 src/rattle_structures.py
            python3 src/make_folders.py
            mv job-sbatch.sh ${{ steps.getshortsha.outputs.sha_short }}-job-sbatch.sh
            sbatch ${{ steps.getshortsha.outputs.sha_short }}-job-sbatch.sh