name: SLURM Queue Workflow

on: 
  push: 
    branches:
      - 'main'

jobs: 
  enqueue:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Get a short version of the GIT commit SHA to use in naming files
        id: getshortsha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Copy files over to the cluster
        uses: garygrossgarten/github-action-scp@v0.6.0 
        with:
          local: ./
          remote: "/users/r/s/${{ secrets.SSH_USERNAME }}/scratch/JOBS/${{ steps.getshortsha.outputs.sha_short }}"
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Execute script to enqueue job in cluster
        uses: appleboy/ssh-action@v0.1.3
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: | 
            cd "/users/r/s/${{ secrets.SSH_USERNAME }}/scratch/JOBS/${{ steps.getshortsha.outputs.sha_short }}"
            python3 src/makefolders.py
            mv job-sbatcher.sh ${{ steps.getshortsha.outputs.sha_short }}-job-sbatch.sh
            sbatch ${{ steps.getshortsha.outputs.sha_short }}-job-sbatch.sh